apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionConfiguration
metadata:
  name: example-promotion-configuration
spec:
apiVersion: promoter.argoproj.io/v1alpha1
spec:
  pullRequest:
    template:
      title: "Promote {{ trunc 5 .ChangeTransferPolicy.Status.Proposed.Dry.Sha }} to `{{ .ChangeTransferPolicy.Spec.ActiveBranch }}`"
      description: "This PR is promoting the environment branch `{{ .ChangeTransferPolicy.Spec.ActiveBranch }}` which is currently on dry sha {{ .ChangeTransferPolicy.Status.Active.Dry.Sha }} to dry sha {{ .ChangeTransferPolicy.Status.Proposed.Dry.Sha }}."
